import "../styles/globals.css";
import "@uploadthing/react/styles.css";

import { ClerkProvider } from '@clerk/nextjs'
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Topnav from "./_components/topnav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "~/components/ui/sonner";
// import { PostHogProvider} from "./_analytics/providers";


export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3000"),
  title: {
    default: "T3 photo store",
    template: "%s | T3 photo store"
  },
  description: "Generated by a loyal subcriber to my photo",
  icons: { icon: "/favicon.ico" }
};



export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode,modal:React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${GeistSans.variable} min-h-screen bg-gradient-to-b from-gray-900 to-gray-800`}>
          <div className="relative">
            <div className="fixed inset-0 bg-[url(/grid.svg)] bg-center [mask-image:linear-gradient(180deg,white,rgba(255,255,255,0))]" />
            <div className="relative">
              <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
              <Topnav />
              <main className="container mx-auto px-4 py-8 overflow-y-auto min-h-screen">
                {children}
              </main>
              {modal}
              <div id="modal-root" />
              <Toaster position="top-center" />
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
