import "../styles/globals.css";
import "@uploadthing/react/styles.css";

import { ClerkProvider } from '@clerk/nextjs'
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Topnav from "./_components/topnav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "~/components/ui/sonner";


export const metadata: Metadata = {
  title: "T3 photo store",
  description: "Generated by a loyal subcriber to my photo",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode,modal:React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" >
      <body className={`${GeistSans.variable} dark`}>
      <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <Topnav/>
        <main className="overflow-y-scroll h-screen dark">{children}</main>
        {modal}
        <div id="modal-root" />
        <Toaster />
        </body>
    </html>
    </ClerkProvider>
  );
}
