import "~/styles/globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Topnav from "./_components/topnav";
export const metadata: Metadata = {
  title: "T3 photo store",
  description: "Generated by a loyal subcriber to my photo",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" >
      <body className={`${GeistSans.variable} flex flex-col gap-4`}>
        <Topnav/>
        {children}</body>
    </html>
    </ClerkProvider>
  );
}
